sudo: true
dist: trusty
language: c

compiler:
  - clang
  
os:
  - linux
  - osx

osx_image: xcode7.3

env:
  - TOOLCHAIN="swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a"
  
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install openssl;
        brew link openssl --force;
        brew tap zewo/tap;
        brew install libvenice;
    fi 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get install -y clang-3.6 libicu-dev;
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.6 100;
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.6 100;
        
        apt-get install libssl-dev

        echo "deb [trusted=yes] http://apt.zewo.io/deb ./" | sudo tee --append /etc/apt/sources.list;
        sudo apt-get update;
        sudo apt-get install libvenice;
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
        wget https://swift.org/builds/development/xcode/${TOOLCHAIN}/${TOOLCHAIN}-osx.pkg;
        pkgutil --expand ${TRAVIS_BUILD_DIR}/${TOOLCHAIN}-osx.pkg ${TRAVIS_BUILD_DIR}/${TOOLCHAIN}-osx.unpkg;
        cat ${TRAVIS_BUILD_DIR}/${TOOLCHAIN}-osx.unpkg/${TOOLCHAIN}-osx-package.pkg/Payload | gunzip -dc |cpio -i;
        export PATH=${TRAVIS_BUILD_DIR}/usr/bin:"${PATH}";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        wget https://swift.org/builds/development/ubuntu1404/${TOOLCHAIN}/${TOOLCHAIN}-ubuntu14.04.tar.gz;
        tar xzf ${TOOLCHAIN}-ubuntu14.04.tar.gz;
        export PATH=${TRAVIS_BUILD_DIR}/${TOOLCHAIN}-ubuntu14.04/usr/bin:"${PATH}";
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      swift build -Xcc -I/usr/local/include -Xlinker -L/usr/local/lib/;
    fi 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        swift build;
    fi
